name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_FIELD_0C8BF3403 }}
          action: "upload"
          app_location: "simple-web-application-setup"  # Folder with your index.html
          api_location: ""                               # No API
          output_location: ""                            # No build output folder
          app_build_command: ""                          # Skip build
